apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventore-mcp.fullname" . }}
  labels:
    {{- include "eventore-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "eventore-mcp.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.mcp.port }}
      name: mcp
