{{- if and .Values.eventore.security.apiToken (not .Values.eventore.security.apiTokenExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eventore.fullname" . }}-api-auth
  labels:
    {{- include "eventore.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.eventore.security.apiTokenSecretKey }}: {{ .Values.eventore.security.apiToken | quote }}
{{- end }}
