apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventore.fullname" . }}-backend
  labels:
    {{- include "eventore.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "eventore.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eventore.fullname" . }}-frontend
  labels:
    {{- include "eventore.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "eventore.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      name: http
